### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Ekgev** [mak-gitdev/HA_enoceanmqtt#55]
Hi, I tried to update from 0.1.21 via the offered update function (See screenshot). Unfortunately nothing happens. Can you please help to update?
![CFDBFEEA-75C6-4253-9E36-C53049DC32F3](https://user-images.githubusercontent.com/118467264/221960563-d221f3db-8322-400d-adc6-cf692809783d.png)

**Comment by mak-gitdev** [comment]
Hi @Ekgev,

See #52

**Comment by Ekgev** [comment]
Thanks a lot. Please let me know which version of your enocean addon should be used in future. .Unfortunately I lost a little bit the overview. Thanks,

**Comment by mak-gitdev** [comment]
At the moment, only the dev version should be used.
I recently marked the master version as deprecated because it is not ready yet.
Starting from master version 0.2, you will have the choice to use either the master or the dev version.
Dev will include the latest features requiring feedbacks from users while master will be the stable version.

I let you close the issue once everything is right for you.

**Comment by Ekgev** [comment]
Thank you very much.
